apiVersion: v1
kind: Service
metadata:
  name: api-cms
  labels:
    app: api-cms
spec:
  type: NodePort
  ports:
    - name: http
      port: 7202
      targetPort: 7202
  selector:
    app: api-cms
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-cms-v1
  labels:
    app: api-cms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-cms
      version: v1
  template:
    metadata:
      labels:
        app: api-cms
        version: v1
    spec:
      restartPolicy: Always
      containers:
        - name: api-cms
          image: liam1803/s1-api-cms:v1.0.0
          ports:
            - name: http
              containerPort: 7202
          env:
            - name: PROJECT_ENV
              value: "test"

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api-cms-ingress
spec:
  rules:
    - host: mn-api-cms.mygs.com
      http:
        paths:
          - path:
            backend:
              serviceName: api-cms
              servicePort: 7202