apiVersion: v1
kind: Service
metadata:
  name: auth-rbac
  labels:
    app: auth-rbac
spec:
  type: ClusterIP
#  externalTrafficPolicy: Local
  ports:
    - name: http
      port: 7042
      targetPort: 7042
  selector:
    app: auth-rbac
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-rbac-v1
  labels:
    app: auth-rbac
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-rbac
      version: v1
  template:
    metadata:
      labels:
        app: auth-rbac
        version: v1
    spec:
      restartPolicy: Always
      containers:
        - name: auth-rbac
          image: liam1803/s1-auth-rbac:v1.0.0
          ports:
            - name: http
              containerPort: 7042
          env:
            - name: PROJECT_ENV
              value: "dev"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: auth-rbac
spec:
  hosts:
    - "mn-auth-rbac.mygs.com" # temp
  gateways:
    - gateway-api/makeblock-gateway-api
  http:
    - route:
        - destination:
            host: auth-rbac
            port:
              number: 7042
