apiVersion: v1
kind: Service
metadata:
  name: auth-jwt
  labels:
    app: auth-jwt
spec:
  type: NodePort
  ports:
    - name: http
      port: 7301
      targetPort: 7301
  selector:
    app: auth-jwt
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-jwt-v1
  labels:
    app: auth-jwt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-jwt
      version: v1
  template:
    metadata:
      labels:
        app: auth-jwt
        version: v1
    spec:
      restartPolicy: Always
      containers:
        - name: auth-jwt
          image: liam1803/s1-auth-jwt:v1.0.1
          ports:
            - name: http
              containerPort: 7301
          env:
            - name: PROJECT_ENV
              value: "test"
            - name: TEMP_STRING
              value: "test1"
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: auth-jwt-ingress
spec:
  rules:
    - host: mn-auth-jwt.mygs.com
      http:
        paths:
          - path:
            backend:
              serviceName: auth-jwt
              servicePort: 7301