apiVersion: v1
kind: Service
metadata:
  name: sv-log
  labels:
    app: sv-log
spec:
  type: NodePort
  ports:
    - name: http
      port: 7403
      targetPort: 7403
  selector:
    app: sv-log
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sv-log-v1
  labels:
    app: sv-log
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sv-log
      version: v1
  template:
    metadata:
      labels:
        app: sv-log
        version: v1
    spec:
      restartPolicy: Always
      containers:
        - name: sv-log
          image: liam1803/s1-sv-log:v1.0.1
          ports:
            - name: http
              containerPort: 7403
          env:
            - name: PROJECT_ENV
              value: "test"
            - name: TEMP_STRING
              value: "test1"
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sv-log-ingress
spec:
  rules:
    - host: mn-sv-log.mygs.com
      http:
        paths:
          - path:
            backend:
              serviceName: sv-log
              servicePort: 7403