global:
    scrape_interval: 5s
    external_labels:
        monitor: 'my-monitor'
scrape_configs:
    - job_name: 'prometheus'
      static_configs:
          - targets: ['localhost:9090']
    - job_name: 'api-www'
      metrics_path: /api-www/metrics/v2  # 采集对象的path路径
      scheme: http  # 采集协议：http或者https
      scrape_interval: 10s
      static_configs:
          - targets: ['10.10.201.30:7001','192.168.31.235:7001']
    - job_name: 'auth-jwt'
      metrics_path: /auth-jwt/metrics/v2  # 采集对象的path路径
      scheme: http  # 采集协议：http或者https
      scrape_interval: 10s
      static_configs:
          - targets: ['192.168.31.235:7001']
    - job_name: 'sv-log'
      metrics_path: /sv-log/metrics/v2  # 采集对象的path路径
      scheme: http  # 采集协议：http或者https
      scrape_interval: 10s
      static_configs:
          - targets: ['192.168.31.235:7001']
rule_files:
  - 'alert.rules'
