apiVersion: v1
kind: Service
metadata:
  name: sv-ai
  labels:
    app: sv-ai
spec:
  type: NodePort
  ports:
    - name: http
      port: 7401
      targetPort: 7401
  selector:
    app: sv-ai
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sv-ai-v1
  labels:
    app: sv-ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sv-ai
      version: v1
  template:
    metadata:
      labels:
        app: sv-ai
        version: v1
    spec:
      restartPolicy: Always
      containers:
        - name: sv-ai
          image: liam1803/s1-sv-ai:v1.0.1
          ports:
            - name: http
              containerPort: 7401
          env:
            - name: PROJECT_ENV
              value: "test"
            - name: TEMP_STRING
              value: "test1"
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sv-ai-ingress
spec:
  rules:
    - host: mn-sv-ai.mygs.com
      http:
        paths:
          - path:
            backend:
              serviceName: sv-ai
              servicePort: 7401