apiVersion: v1
kind: Service
metadata:
  name: api-cms
  labels:
    app: api-cms
spec:
  type: ClusterIP
#  externalTrafficPolicy: Local
  ports:
    - name: http
      port: 7042
      targetPort: 7042
  selector:
    app: api-cms
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-cms-v1
  labels:
    app: api-cms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-cms
      version: v1
  template:
    metadata:
      labels:
        app: api-cms
        version: v1
    spec:
      restartPolicy: Always
      containers:
        - name: api-cms
          image: liam1803/s1-api-cms:v1.0.0
          ports:
            - name: http
              containerPort: 7042
          env:
            - name: PROJECT_ENV
              value: "dev"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: api-cms
spec:
  hosts:
    - "mn-api-cms.mygs.com" # temp
  gateways:
    - gateway-api/makeblock-gateway-api
  http:
    - route:
        - destination:
            host: api-cms
            port:
              number: 7042
