apiVersion: v1
kind: Service
metadata:
  name: sv-mq
  labels:
    app: sv-mq
spec:
  type: NodePort
  ports:
    - name: http
      port: 7404
      targetPort: 7404
  selector:
    app: sv-mq
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sv-mq-v1
  labels:
    app: sv-mq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sv-mq
      version: v1
  template:
    metadata:
      labels:
        app: sv-mq
        version: v1
    spec:
      restartPolicy: Always
      containers:
        - name: sv-mq
          image: liam1803/s1-sv-mq:v1.0.1
          ports:
            - name: http
              containerPort: 7404
          env:
            - name: PROJECT_ENV
              value: "test"
            - name: TEMP_STRING
              value: "test1"
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sv-mq-ingress
spec:
  rules:
    - host: mn-sv-mq.mygs.com
      http:
        paths:
          - path:
            backend:
              serviceName: sv-mq
              servicePort: 7404