apiVersion: v1
kind: Service
metadata:
  name: sv-config
  labels:
    app: sv-config
spec:
  type: ClusterIP
#  externalTrafficPolicy: Local
  ports:
    - name: http
      port: 7042
      targetPort: 7042
  selector:
    app: sv-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sv-config-v1
  labels:
    app: sv-config
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sv-config
      version: v1
  template:
    metadata:
      labels:
        app: sv-config
        version: v1
    spec:
      restartPolicy: Always
      containers:
        - name: sv-config
          image: liam1803/s1-sv-config:v1.0.0
          ports:
            - name: http
              containerPort: 7042
          env:
            - name: PROJECT_ENV
              value: "dev"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: sv-config
spec:
  hosts:
    - "mn-sv-config.mygs.com" # temp
  gateways:
    - gateway-api/makeblock-gateway-api
  http:
    - route:
        - destination:
            host: sv-config
            port:
              number: 7042
