apiVersion: v1
kind: Service
metadata:
  name: sv-region
  labels:
    app: sv-region
spec:
  type: NodePort
  ports:
    - name: http
      port: 7409
      targetPort: 7409
  selector:
    app: sv-region
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sv-region-v1
  labels:
    app: sv-region
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sv-region
      version: v1
  template:
    metadata:
      labels:
        app: sv-region
        version: v1
    spec:
      restartPolicy: Always
      containers:
        - name: sv-region
          image: liam1803/s1-sv-region:v1.0.0
          ports:
            - name: http
              containerPort: 7409
          env:
            - name: PROJECT_ENV
              value: "test"

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sv-region-ingress
spec:
  rules:
    - host: mn-sv-region.mygs.com
      http:
        paths:
          - path:
            backend:
              serviceName: sv-region
              servicePort: 7409