version: '3.7'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
      - "14269:14269"
    networks:
      - jaeger-example
#  hotrod:
#    image: jaegertracing/example-hotrod:latest
#    ports:
#      - "7041:8080"
#    command: ["all"]
#    environment:
#      - JAEGER_AGENT_HOST=jaeger
#      - JAEGER_AGENT_PORT=6831
#    networks:
#      - jaeger-example
#    depends_on:
#      - jaeger

networks:
  jaeger-example: