apiVersion: v1
kind: Service
metadata:
  name: sv-user
  labels:
    app: sv-user
spec:
  type: NodePort
  ports:
    - name: http
      port: 7407
      targetPort: 7407
  selector:
    app: sv-user
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sv-user-v1
  labels:
    app: sv-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sv-user
      version: v1
  template:
    metadata:
      labels:
        app: sv-user
        version: v1
    spec:
      restartPolicy: Always
      containers:
        - name: sv-user
          image: liam1803/s1-sv-user:v1.0.0
          ports:
            - name: http
              containerPort: 7407
          env:
            - name: PROJECT_ENV
              value: "test"
            - name: TEMP_STRING
              value: "test2"
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sv-user-ingress
spec:
  rules:
    - host: mn-sv-user.mygs.com
      http:
        paths:
          - path:
            backend:
              serviceName: sv-user
              servicePort: 7407