apiVersion: v1
kind: Service
metadata:
  name: api-www
  labels:
    app: api-www
spec:
  type: NodePort
  ports:
    - name: http
      port: 7203
      targetPort: 7203
  selector:
    app: api-www
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-www-v1
  labels:
    app: api-www
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-www
      version: v1
  template:
    metadata:
      labels:
        app: api-www
        version: v1
    spec:
      restartPolicy: Always
      containers:
        - name: api-www
          image: liam1803/s1-api-www:v1.0.1
          ports:
            - name: http
              containerPort: 7203
          env:
            - name: PROJECT_ENV
              value: "test"
            - name: TEMP_STRING
              value: "test1"
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api-www-ingress
spec:
  rules:
    - host: mn-api-www.mygs.com
      http:
        paths:
          - path:
            backend:
              serviceName: api-www
              servicePort: 7203