apiVersion: v1
kind: Service
metadata:
  name: sv-money
  labels:
    app: sv-money
spec:
  type: NodePort
  ports:
    - name: http
      port: 7408
      targetPort: 7408
  selector:
    app: sv-money
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sv-money-v1
  labels:
    app: sv-money
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sv-money
      version: v1
  template:
    metadata:
      labels:
        app: sv-money
        version: v1
    spec:
      restartPolicy: Always
      containers:
        - name: sv-money
          image: liam1803/s1-sv-money:v1.0.0
          ports:
            - name: http
              containerPort: 7408
          env:
            - name: PROJECT_ENV
              value: "test"

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sv-money-ingress
spec:
  rules:
    - host: mn-sv-money.mygs.com
      http:
        paths:
          - path:
            backend:
              serviceName: sv-money
              servicePort: 7408