apiVersion: v1
kind: Service
metadata:
  name: gateway-api
  labels:
    app: gateway-api
spec:
  type: ClusterIP
  #externalTrafficPolicy: Local
  ports:
    - name: http
      port: 80
      targetPort: 7001
  selector:
    app: gateway-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-api-v1
  labels:
    app: gateway-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-api
      version: v1
  template:
    metadata:
      labels:
        app: gateway-api
        version: v1
    spec:
      restartPolicy: Always
      containers:
        - name: gateway-api
          image: liam1803/s1-gateway-api:v1.0.0
          ports:
            - name: http
              containerPort: 7001
          env:
            - name: PROJECT_ENV
              value: "dev"
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: s1-gateway-api-ingress
spec:
  rules:
    - host: gateway-api-pre.mygs.com
      http:
        paths:
          - path:
            backend:
              serviceName: gateway-api
              servicePort: 80
