apiVersion: v1
kind: Service
metadata:
  name: sv-oss
  labels:
    app: sv-oss
spec:
  type: NodePort
  ports:
    - name: http
      port: 7406
      targetPort: 7406
  selector:
    app: sv-oss
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sv-oss-v1
  labels:
    app: sv-oss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sv-oss
      version: v1
  template:
    metadata:
      labels:
        app: sv-oss
        version: v1
    spec:
      restartPolicy: Always
      containers:
        - name: sv-oss
          image: liam1803/s1-sv-oss:v1.0.1
          ports:
            - name: http
              containerPort: 7406
          env:
            - name: PROJECT_ENV
              value: "test"
            - name: TEMP_STRING
              value: "test2"
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sv-oss-ingress
spec:
  rules:
    - host: mn-sv-oss.mygs.com
      http:
        paths:
          - path:
            backend:
              serviceName: sv-oss
              servicePort: 7406