apiVersion: v1
kind: Service
metadata:
  name: api-app
  labels:
    app: api-app
spec:
  type: NodePort
  ports:
    - name: http
      port: 7201
      targetPort: 7201
  selector:
    app: api-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-app-v1
  labels:
    app: api-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-app
      version: v1
  template:
    metadata:
      labels:
        app: api-app
        version: v1
    spec:
      restartPolicy: Always
      containers:
        - name: api-app
          image: liam1803/s1-api-app:v1.0.0
          ports:
            - name: http
              containerPort: 7201
          env:
            - name: PROJECT_ENV
              value: "test"

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api-app-ingress
spec:
  rules:
    - host: mn-api-app.mygs.com
      http:
        paths:
          - path:
            backend:
              serviceName: api-app
              servicePort: 7201