apiVersion: v1
kind: Service
metadata:
  name: sv-config
  labels:
    app: sv-config
spec:
  type: NodePort
  ports:
    - name: http
      port: 7402
      targetPort: 7402
  selector:
    app: sv-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sv-config-v1
  labels:
    app: sv-config
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sv-config
      version: v1
  template:
    metadata:
      labels:
        app: sv-config
        version: v1
    spec:
      restartPolicy: Always
      containers:
        - name: sv-config
          image: liam1803/s1-sv-config:v1.0.1
          ports:
            - name: http
              containerPort: 7402
          env:
            - name: PROJECT_ENV
              value: "test"
            - name: TEMP_STRING
              value: "test1"
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sv-config-ingress
spec:
  rules:
    - host: mn-sv-config.mygs.com
      http:
        paths:
          - path:
            backend:
              serviceName: sv-config
              servicePort: 7402